#!/usr/bin/env bash
# Superstitous number

i=1
while [ "$i" -lt 21 ]; do
   if [ "$i" -eq 4 ]; then
      echo "bad luck from China"
   elif [ "$i" -eq 9 ]; then
      echo "bad luck from Japan"
   elif [ "$i" -eq 17 ]; then
      echo "bad luck from Italy"
   else echo "$i"
   fi
   ((i++))
done
