#!/usr/bin/env bash
# Superstitous number

count=1

while [ $count -le 20 ]; do
    case $count in
        4)
            echo "Bad luck from China"
            ;;
        9)
            echo "Bad luck from Japan"
            ;;
        17)
            echo "Bad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac
    ((count++))
done

